# Generated by Django 5.2.14 on 2026-05-06 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("market", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("CREATED", "Created"),
                    ("AWAITING_PICKUP_SCHEDULING", "Awaiting pickup"),
                    ("SCHEDULED", "Scheduled"),
                    ("READY_FOR_PICKUP", "Ready for pickup"),
                    ("COMPLETE", "Complete"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="CREATED",
                max_length=40,
            ),
        ),
    ]
