# Generated by Django 5.2.12 on 2026-04-04 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="GeocodeCache",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address_hash", models.CharField(max_length=64, unique=True)),
                ("normalized_address", models.TextField()),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
                ("confidence", models.CharField(blank=True, max_length=20)),
                ("provider", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="DistributionCenter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address_line1", models.CharField(max_length=255)),
                ("address_line2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=100)),
                ("postal_code", models.CharField(max_length=20)),
                ("country", models.CharField(default="US", max_length=2)),
                ("lat", models.FloatField(blank=True, null=True)),
                ("lon", models.FloatField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PROPOSED", "Proposed"),
                            ("APPROVED", "Approved"),
                            ("REJECTED", "Rejected"),
                            ("INACTIVE", "Inactive"),
                        ],
                        default="PROPOSED",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("capacity_per_day", models.PositiveIntegerField(default=50)),
                ("pickup_windows", models.JSONField(blank=True, default=list)),
                (
                    "proposed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CenterSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "capacity_override",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("pickup_windows", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True)),
                (
                    "center",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="schedules",
                        to="logistics.distributioncenter",
                    ),
                ),
            ],
            options={
                "unique_together": {("center", "date")},
            },
        ),
    ]
