# Generated by Django 5.2.12 on 2026-04-04 16:38

import django.db.models.deletion
import sensors.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("gardens", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SensorDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("type", models.CharField(max_length=100)),
                ("location_tag", models.CharField(blank=True, max_length=100)),
                (
                    "api_token",
                    models.CharField(
                        default=sensors.models._generate_token,
                        max_length=64,
                        unique=True,
                    ),
                ),
                (
                    "gardener",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="devices",
                        to="gardens.gardenerprofile",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SensorReading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField()),
                ("metric", models.CharField(max_length=100)),
                ("value", models.FloatField()),
                ("unit", models.CharField(max_length=50)),
                (
                    "device",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="readings",
                        to="sensors.sensordevice",
                    ),
                ),
            ],
        ),
    ]
